title: '方子东的 blog'
description: '方子东 blog 技术blog 技术博客 tech blog quaeast'
markdown:
  lineNumbers: true
themeConfig: 
  sidebarDepth: 3
  nav:
    - text: 'GitHub'
      link: 'https://github.com/quaeast'
      target: '_blank'
  sidebar: 'auto'
  lastUpdated: 'Last Updated'
  smoothScroll: true
